package com.arvaan.contactsfirebase.utils

// INTENT SELECTION
const val KEY_INTENT_SELECTION = "KEY_INTENT_SELECTION"
const val KEY_INTENT_UPDATE = "KEY_INTENT_EDIT"
const val KEY_INTENT_ADD = "KEY_INTENT_ADD"

// INTENT ATTACHMENTS
const val KEY_DATABASE_ITEM_KEY = "KEY_ID"
const val KEY_FIRST_NAME = "KEY_FIRST_NAME"
const val KEY_LAST_NAME = "KEY_LAST_NAME"
const val KEY_EMAIL_ID = "KEY_EMAIL_ID"
const val KEY_PHONE_NUMBER = "KEY_PHONE_NUMBER"
const val KEY_IMAGE_URL = "KEY_IMAGE_URL"
const val KEY_BIRTH_DATE = "KEY_BIRTH_DATE"

// FIREBASE PATH
const val STORAGE_FOLDER_NAME = "images"
const val DATABASE_PATH_CONTACT = "contacts"

// FIREBASE STATUS
const val FIREBASE_STATUS_STARTED = "FIREBASE_STATUS_STARTED"
//const val FIREBASE_COMPLETED = "FIREBASE_STATUS_COMPLETED"

const val FIREBASE_COMPLETED_UPLOADING_IMAGE = "FIREBASE_COMPLETED_UPLOADING_IMAGE"
const val FIREBASE_FAILED_UPLOADING_IMAGE = "FIREBASE_FAILED_UPLOADING_IMAGE"

const val FIREBASE_COMPLETED_DELETING_IMAGE = "FIREBASE_COMPLETED_DELETING_IMAGE"
const val FIREBASE_FAILED_DELETING_IMAGE = "FIREBASE_FAILED_DELETING_IMAGE"

const val FIREBASE_COMPLETED_SAVING_CONTACT = "FIREBASE_COMPLETED_SAVING_CONTACT"
const val FIREBASE_FAILED_SAVING_CONTACT = "FIREBASE_FAILED_SAVING_CONTACT"

const val FIREBASE_COMPLETED_UPDATING_CONTACT = "FIREBASE_COMPLETED_UPDATING_CONTACT"
const val FIREBASE_FAILED_UPDATING_CONTACT = "FIREBASE_FAILED_UPDATING_CONTACT"

const val FIREBASE_COMPLETED_DELETING_CONTACT = "FIREBASE_COMPLETED_DELETING_CONTACT"
const val FIREBASE_FAILED_DELETING_CONTACT = "FIREBASE_FAILED_DELETING_CONTACT"

const val FIREBASE_COMPLETED_RETRIEVING_CONTACTS = "FIREBASE_COMPLETED_RETRIEVING_CONTACTS"
const val FIREBASE_FAILED_RETRIEVING_CONTACTS = "FIREBASE_FAILED_RETRIEVING_CONTACTS"



